### ISSUE TITLE
关于Pass检测代码的几个问题

### ISSUE THREAD

**Issue by Tomahawkd** [younaman/AR-Attack#1]
您好，看了文章之后我想复现一下您在文章里提到的这个程序。但是我在运行中碰到几个问题和几处错误的地方想请教一下。
注：该issue已同步提交到[ZJU-SEC/AbstractResourceAttack](https://github.com/ZJU-SEC/AbstractResourceAttack/issues/2)

1. LockPair.cpp中获取元素type的错误
在[995行](https://github.com/ZJU-SEC/AbstractResourceAttack/blob/61fda8e9b81ca7525adce07938a90fb84e99586b/AbstractResourceDos/LockPair.cpp#L995)和[1059行](https://github.com/ZJU-SEC/AbstractResourceAttack/blob/61fda8e9b81ca7525adce07938a90fb84e99586b/AbstractResourceDos/LockPair.cpp#L1059)中
```c++
llvm::Type *ArrayTy = RealmType->getPointerElementType();
```
是否应为
```c++
llvm::Type *ArrayTy = RealmType->getArrayElementType();
```
实际运行中会产生assert错误，修复后正常。

2. LockPair.cpp中FindChangArg函数中可能出现offset越界的情况
在[282行](https://github.com/ZJU-SEC/AbstractResourceAttack/blob/61fda8e9b81ca7525adce07938a90fb84e99586b/AbstractResourceDos/LockPair.cpp#L282)
```c++
bool LockPair::FindChangArg(llvm::Function * funcname, int offset){//这里相当于输入了funcA: call funcB中的funcB和对应指针类型函数的偏移量
    std::cout<<"into FindChangeArg"<<std::endl;
    if(llvm::Value * offsetarg=funcname->getArg(offset)){
...
```
目前我也没有定位出该错误的具体原因，所以我加了一次if判断
```c++
if (funcname->arg_size() <= offset) return false;
```

3. CtlTableAnalysis.cpp中错误的类型转换
在[159行](https://github.com/ZJU-SEC/AbstractResourceAttack/blob/61fda8e9b81ca7525adce07938a90fb84e99586b/AbstractResourceDos/CtlTableAnalysis.cpp#L159)中，该类型被强制转换成`llvm::ConstantStruct`，但是在实际运行中发现可能会出现`llvm::Constant`类，导致转换失败。
```c++
llvm::ConstantStruct *CS=llvm::cast<llvm::ConstantStruct>(GlobalVInitList->getOperand(Index));
```
目前我修改为
```c++
llvm::ConstantStruct *CS=llvm::dyn_cast<llvm::ConstantStruct>(GlobalVInitList->getOperand(Index));
if (!CS) continue;
```
来忽略`llvm::Constant`类。

修改为这三处之后我得到的运行结果：
```
Total Struct Type: 153
Total Global Variable: 18
Total Function: 641
```
但是该结果和论文中的结果有些偏差。

-----------------------------
环境和Linux内核配置情况：
cmake: 3.18.1预编译包
clang+llvm: 12.0预编译包
linux: 5.3.1
python: 3.8.10
wllvm: 1.3.1
其中，linux编译命令如下：
```bash
# 默认配置
make CC=wllvm HOSTCC=wllvm defconfig
make CC=wllvm HOSTCC=wllvm
```
其余操作均遵循README。

谢谢。

**Comment by younaman** [comment]
@Tomahawkd 感谢您的关注！这个版本的代码和论文当时使用的代码并不完全一致。论文中使用的代码没有“变量是否为量化修改"部分；对于论文中的结果，我们是先找到了"锁保护了对变量的修改"之后手工筛掉了非量化修改的部分。你可以尝试在这版代码基础上去掉"判断是否是量化修改后结果"再做尝试

**Comment by younaman** [comment]
@Tomahawkd 另外由于我论文中使用了PeX的现有工具作为syscall reachable分析工具，因此我印象里面运行llvm时需要添加额外的参数以启用PeX的间接call分析(具体参数我忘记了，您可以联系PeX作者进行询问)，您是否添加了参数？如果缺少运行参数，确实会丢掉大量间接call分析的结果。另外还有其它细节(比如关闭内联，我在论文中提到了)您是否也注意到了？如果您有其它问题，十分欢迎和我交流:)

**Comment by Tomahawkd** [comment]
关于syscall reachable我并没有添加参数，我目前也只是初步对代码运行复现一下，这个我再关注一下。关于内联，我是使用了您的test.sh文件，不知道是否正确。这一块我在网上[查询到的代码](https://gist.github.com/richardchien/0ef27ce80337a797dcfe245944dd6f95)和这个test.sh非常像，就直接用的repo的了。另外，还有一些其他的细节例如修改LLVM的部分我也还没有操作，编译器这块我没有经验，所以暂时还是使用的预编译包。

**Comment by younaman** [comment]
@Tomahawkd 我估计问题是主要出在了没有添加参数上，这会导致PeX只分析direct call,漏掉大量间接call的结果

**Comment by Tomahawkd** [comment]
好的，我再关注一下这块，谢谢

**Comment by Tomahawkd** [comment]
另外，可以麻烦您能否提供一下您当时运行或者筛选后的结果？谢谢

**Comment by younaman** [comment]
@Tomahawkd 我主要隔得时间太久了，不确定能不能找到当时得结果。建议你先开启PeX间接call分析之后自己跑一个结果出来，如果大差不差应该就可以用

**Comment by Tomahawkd** [comment]
好的，我这边先试一下吧。
